"""
Mitigated Package - Main Launch Point for Mitigated Models

This package contains the primary execution scripts and output directories for the
mitigation strategy experiments.

Scripts:
    - launch.py: Main entry point for running mitigated model experiments
    - launch2.py, launch3.py, etc.: Alternative experimental configurations

Output Directories:
    - GeneratedImages/: Synthetic images generated by diffusion models
    - Model results organized by culture (CI, CJ, CS, LC, LF, LT)
    - Confidence threshold subfolders (0.05, 0.2, 0.3)
    - Preprocessing logs and discriminator results

Key Features:
    - Culture-bias mitigation with custom regularization
    - Diffusion-based synthetic data augmentation
    - Optional adversarial robustness testing
    - Culture-balanced training
"""
